export type SHAPE_RENDER_TYPE = 'auto' | 'optimizeSpeed' | 'crispEdges' | 'geometricPrecision';


export const IS_WEB = (function() {
  try {
    return !!process.env.REACT_APP_WEB_ACTIVE;
  } catch (e) {
    return false;
  }
})();

export const LEAD_NAMES = ['II', 'V1'];

export const SAMPLING_RATE = 360;
export const SEGMENT_DURATION = 10;
export const SEGMENT_LENGTH = SAMPLING_RATE * SEGMENT_DURATION;

export const SPEED_ARRAY = [0, 0.5, 1, 5, 10];

export const PLOT_LINE_COLOR = '#001F4A';

/* DISEASES INFO */
export const DISEASES = ['SR', 'AF', 'PR', 'LBBB', 'RBBB', 'PVC'];
export const DISEASES_NAME_MAP: { [key: string]: string } = {
  SR: 'Sinus Rhythm (SR)',
  AF: 'Atrial Fibrillation (AF)',
  PR: 'Paced Rhythm (PR)',
  LBBB: 'Left bundle branch block (LBBB)',
  RBBB: 'Right bundle branch block (RBBB)',
  PVC: 'Premature ventricular contractions (PVC)',
};
export const DISEASES_DESC_MAP: { [key: string]: string } = {
  SR: 'Sinus rhythm is characterized by the presence of correctly oriented P waves on the electrocardiogram (ECG). It is necessary, but not sufficient, for normal electrical activity within the heart.',
  AF: 'Atrial fibrillation, often called AF, is characterized by irregular and often very rapid heart rhythm.',
  PR: 'A Paced Rhythm is a type of heart rhythm that is generated by a device called a pacemaker. Pacemakers are small electronic devices that are placed in the chest or abdomen and are used to treat abnormal heart rhythms (arrhythmias). The pacemaker sends electrical signals to the heart to help it maintain a normal heart rate. PR can be seen on an ECG as a series of regular, evenly spaced electrical impulses.',
  LBBB: 'Left bundle branch block is a conduction abnormality in the heart that can be seen on an ECG recording. In this condition, activation of the left ventricle of the heart is delayed, which causes the left ventricle to contract later than the right ventricle. Wide QRS complexes in adults or narrow QRS complexes in children characterize the ECG of an LBBB.',
  RBBB: 'Right bundle branch block is a heart block in the right bundle branch of the electrical conduction system. Wide and deflected QRS complexes characterize the ECG of an RBBB.',
  PVC: 'A Premature ventricular contractions is a common event where the heartbeat is initiated by Purkinje fibers in the ventricles rather than by the sinoatrial node. PVCs may cause no symptoms or may be perceived as a "skipped beat" or felt as palpitations in the chest. However, very frequent PVCs can be symptomatic of an underlying heart condition. The electrical events of the heart detected by the ECG allow a PVC to be easily distinguished from a normal heartbeat',
};
